---
linters-settings:
  govet:
    check-shadowing: true

linters:
  enable:
    - bodyclose
    - gocognit
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - stylecheck
    - typecheck
    - unparam
    - whitespace
