---
version: 2.1

orbs:
  go: circleci/go@1
  semantic-release: trustedshops-public/semantic-release@6

jobs:
  ko-build:
    executor:
      name: go/default
      tag: '1.21'
    parameters:
      push:
        default: false
        type: boolean
      tags:
        default: ""
        type: string
    environment:
      KO_VERSION: "0.15.1"
      KO_DOCKER_REPO: "ghcr.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
      KOCACHE: "1"
    steps:
      - checkout
      - run:
          name: Install KO
          command: |
            curl -sSfL \
            "https://github.com/ko-build/ko/releases/download/v${KO_VERSION}/ko_${KO_VERSION}_Linux_x86_64.tar.gz" \
            | tar -xz -C ~/bin/
      - run:
          name: Build Container
          command: >-
            ko build
            --base-import-paths
            --platform=all
            <<^ parameters.push >> --local <</ parameters.push >>
            --tags="<< parameters.tags >>"
            .

workflows:
  continuous:
    jobs:
      - ko-build:
          context: github
      - semantic-release/with_minimal_github_config:
          name: semantic-release
          context: github
          filters:
            branches:
              only:
                - main
          requires:
            - ko-build
  tags:
    jobs:
      - ko-build:
          context: github
          push: true
          tags: "$CIRCLE_TAG,latest"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
