version: 2.1
orbs:
  go: circleci/go@4
jobs:
  draft-release:
    executor:
      name: go/default
      tag: "1.26"
    resource_class: small
    steps:
      - checkout
      - run:
          name: go-semantic-release
          command: |
            curl -sSL https://get-release.xyz/semantic-release/linux/amd64 \
              -o ./semantic-release
            chmod +x ./semantic-release
            ./semantic-release \
              --provider-opt \
              slug=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
              --allow-no-changes \
              --prerelease \
              --allow-initial-development-versions
  release:
    executor:
      name: go/default
      tag: '1.26'
    steps:
      - checkout
      - go/install-goreleaser
      - go/goreleaser-release:
          publish-release: true
          validate-yaml: true
  test:
    executor:
      name: go/default
      tag: '1.26'
    steps:
      - checkout
      - go/mod-download
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  continuous:
    jobs:
      - test
      - draft-release:
          context: github
          filters:
            branches:
              only:
                - main
          requires:
            - test
  tags:
    jobs:
      - release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
