---
version: 2.1

orbs:
  go: circleci/go@1
  semantic-release: trustedshops-public/semantic-release@6

jobs:
  build:
    executor:
      name: go/default
      tag: '1.21'
    parameters:
      push:
        type: boolean
        default: false
    steps:
      - checkout
      - go/mod-download
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - go/install-goreleaser
      - go/goreleaser-release:
          publish-release: << parameters.push >>
          validate-yaml: true

workflows:
  continuous:
    jobs:
      - build:
          context: github
      - semantic-release/with_minimal_github_config:
          name: semantic-release
          context: github
          filters:
            branches:
              only:
                - main
          requires:
            - build
  tags:
    jobs:
      - build:
          context: github
          push: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
